language: go

go:
  - 1.13.15

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -v -cover $(go list ./... | grep -v /vendor/) -race
